#!/usr/bin/env bash

# Initalize aliases - NOT idempotent
(cd ~/shell-configuration; ./pull.sh)
cp ~/shell-configuration/configuration/.bash_device ~/.bash_device
echo "source ~/.bash_device" >> ~/.bashrc
echo "source ~/.bash_functions" >> ~/.bashrc
echo "source ~/.bash_aliases" >> ~/.bashrc
echo "Shell configuration successfully initialized"
