#!/usr/bin/env bash

if [[ $(git status --porcelain) ]]; then
  echo "There are changes. Please review and commit them before pushing"
  exit 1
fi

git pull

if [ -f ~/.bash_aliases ]; then
    rm configuration/.bash_aliases
    cp ~/.bash_aliases configuration/.bash_aliases
fi

if [ -f ~/.bash_functions ]; then
    rm configuration/.bash_functions
    cp ~/.bash_functions configuration/.bash_functions
fi

if [ -f ~/.tmux.conf ]; then
    rm configuration/.tmux.conf
    cp ~/.tmux.conf configuration/.tmux.conf
fi

git add .
git commit -m "[script] shell configuration update"
git push

echo "Pushed shell configuration"
